// apps/client-app/src/app/components/alert.component.tsx
import React, { FunctionComponent } from 'react';

export enum AlertType {
    SUCCESS = 'success',
    DANGER = 'danger',
    PRIMARY = 'primary'
}

export const Alert: FunctionComponent<{ message: string, type: AlertType}> = ({message, type}) => {
    return (
        <div className={`alert alert-${type}`} role="alert">
            { message }
        </div>
    )
};

// apps/admin-panel/src/app/components/alert/alert.component.ts
import { Component, Input } from '@angular/core';

export enum AlertType {
    SUCCESS = 'success',
    DANGER = 'danger',
    PRIMARY = 'primary'
}

@Component({
    selector: 'tin-alert',
    templateUrl: './alert.component.html'
})
export class AlertComponent {
    @Input() type: AlertType;
    @Input() message: string;
}

<div class="alert alert-{{type}}" role="alert">
    {{ message }}
</div>
