// apps/admin-panel/src/app/components/header/header.component.ts
import { ChangeDetectionStrategy, Component, HostListener, OnInit } from '@angular/core';
import { select, Store } from '@ngrx/store';
import { State } from '../../+state';
import { authQuery } from '../../+state/auth/auth.selectors';
import { Observable } from 'rxjs';
import { ordersQuery } from '../../+state/orders/orders.selectors';
import { Directory, Restaurant } from '@bon-appetit/interfaces';
import { Logout } from '../../+state/auth/auth.actions';
import { FormControl } from '@angular/forms';
import { debounceTime, distinctUntilChanged, switchMap } from 'rxjs/operators';
import { RestaurantsService } from '../../+state/restaurants/restaurants.service';
import { Router } from '@angular/router';

@Component({
    selector: 'tin-header',
    templateUrl: './header.component.html',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class HeaderComponent implements OnInit {
    isAuthenticated$: Observable<boolean> = this.store.pipe(select(authQuery.getAuthenticated));
    email$: Observable<string> = this.store.pipe(select(authQuery.getEmail));
    getSumOrders$: Observable<number> = this.store.pipe(select(ordersQuery.getSumOrders));
    userRole$: Observable<Directory> = this.store.pipe(select(authQuery.getUserRole));

    constructor(private store: Store<State>,
                private restaurantsService: RestaurantsService,
                private router: Router) {}

    collapseDropdown = false;
    show = false;
    results: Restaurant[] = [];
    queryField: FormControl = new FormControl();

    @HostListener('document:click', ['$event'])
    onDocumentClick(): void {
        this.show = false;
    }

    ngOnInit() {
        this.queryField.valueChanges
            .pipe(
                debounceTime(300),
                distinctUntilChanged(),
                switchMap(searchQuery => {
                    return this.restaurantsService.searchRestaurant(searchQuery);
                })
            )
            .subscribe(restaurants => {
                this.show = true;
                this.results = restaurants;
            });
    }

    moveToRestaurant(id: number): void {
        this.router.navigate(['restaurant', id]);
    }

    showDropDown(): void {
        this.collapseDropdown = !this.collapseDropdown;
    }

    logout(): void {
        this.store.dispatch(Logout());
    }
}

<header class="section-header">
    <nav
        [ngClass]="(userRole$ | async)?.id > 1 ? 'bg-success' : 'bg-primary'"
        class="navbar navbar-dark navbar-expand p-0">
        <div class="container">
            <ul class="navbar-nav d-none d-md-flex mr-auto">
                <li class="nav-item"><a class="nav-link" [routerLink]="['/users']">Lista użytkowników</a></li>
                <li class="nav-item"><a class="nav-link" [routerLink]="['/restaurants']">Lista restauracji</a></li>
                <li class="nav-item"><a class="nav-link" [routerLink]="['/companies']">Lista firm</a></li>
            </ul>

            <ul class="navbar-nav">
                <li class="nav-item"><a href="#" class="nav-link"> Telefon: +99812345678 </a></li>
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"> Polski </a>
                </li>
            </ul>
            <!-- list-inline //  -->
        </div>
        <!-- navbar-collapse .// -->
        <!-- container //  -->
    </nav>


    <section class="header-main border-bottom">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-2 col-4">
                    <a [routerLink]="['/']" class="brand-wrap">
                        <img class="logo" src="../../../assets/logo.png" />
                    </a>
                    <!-- brand-wrap.// -->
                </div>

                <div class="col-lg-6 col-sm-12">
                    <div
                        *ngIf="(userRole$ | async)?.id <= 1"
                        class="search">
                        <div class="input-group w-100">
                            <input [formControl]="queryField" type="text" class="form-control" placeholder="Search" />

                            <ul *ngIf="results.length"
                                [ngClass]="{'d-none': !show}"
                                class="list-group search"
                            >
                                <li
                                    *ngFor="let result of results"
                                    class="list-group-item btn-link"
                                    (click)="moveToRestaurant(result.id)"
                                >{{ result.name }}</li>
                            </ul>

                            <div class="input-group-append">
                                <button class="btn btn-primary" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                    <!-- search-wrap .end// -->
                </div>
                <!-- col.// -->

                <div class="col-lg-4 col-sm-6 col-12">
                    <div class="widgets-wrap float-md-right">
                        <div class="widget-header mr-3">
                            <a
                                *ngIf="(userRole$ | async)?.id > 1 else orders"
                                [routerLink]="['company']" class="icon icon-sm rounded-circle border">
                                <i class="fa fa-briefcase"></i>
                            </a>

                            <ng-template #orders>
                                <a [routerLink]="['orders']" class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></a>
                                <span class="badge badge-pill badge-danger notify">{{ getSumOrders$ | async }}</span>
                            </ng-template>
                        </div>

                        <div class="widget-header icontext">
                            <div *ngIf="isAuthenticated$ | async; else loginTemplate"
                                 [ngClass]="collapseDropdown ? 'show' : null"
                                 (click)="showDropDown()"
                                 class="dropdown d-inline-block">
                                <div class="icontext mr-4 dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    <div class="icon icon-sm rounded-circle border">
                                        <i class="fa fa-user"></i>
                                    </div>

                                    <div class="text"
                                         *ngIf="(userRole$ | async) as userRole"
                                    >
                                        {{ email$ | async }}
                                        <br/>
                                        Konto: <b>{{ userRole.name }}</b>
                                    </div>
                                </div> <!-- iconbox // -->

                                <div
                                    [ngClass]="collapseDropdown ? 'show' : null"
                                    class="dropdown-menu dropdown-menu-right" x-placement="bottom-end" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 40px, 0px);">
                                    <button class="dropdown-item" [routerLink]="['user']">Profil</button>

                                    <button class="dropdown-item" type="button" (click)="logout()">
                                        <span class="text">Wyloguj</span>
                                    </button>
                                </div>
                            </div>

                            <ng-template #loginTemplate>
                                <div class="text">
                                    <span class="text-muted">Witaj!</span>

                                    <div>
                                        <a [routerLink]="['login']">Zaloguj się</a> |
                                        <a [routerLink]="['register']">Rejestracja</a>
                                    </div>
                                </div>
                            </ng-template>
                        </div>
                    </div>
                    <!-- widgets-wrap.// -->
                </div>
                <!-- col.// -->
            </div>
            <!-- row.// -->
        </div>
        <!-- container.// -->
    </section>
    <!-- header-main .// -->
</header>

// apps/client-app/src/app/components/header.component.tsx
import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useDispatch, useSelector } from 'react-redux';
import { State } from '../+state';
import classNames from 'classnames';
import { logoutAction } from '../+state/auth/auth.actions';
import { fetchOrdersAction } from '../+state/orders/orders.actions';
import { useDebouncedCallback } from 'use-debounce';
import { searchRestaurant } from '../+state/restaurants/restaurants.service';
import { historyRouter } from '../router/history';

export const Header = () => {
    const [collapseDropdown, setCollapseDropdown] = useState(false);
    const [results, setResults] = useState([]);
    const [showSearch, setShowSearch] = useState(false);

    const user = useSelector((state: State) => state.authData.user);

    const sumOrder = useSelector((state: State) => {
        const orders = state.ordersData.orders;

        let sumOrders = 0;

        orders
            .filter(order => order.paid === 0)
            .forEach(order => {
                sumOrders += order.count;
            });

        return sumOrders;
    });
    const dispatch = useDispatch();

    const logout = () => {
        dispatch(logoutAction());
    };

    useEffect(() => {
        if (user) {
            dispatch(fetchOrdersAction(user.id));
        }
    });

    const [debouncedCallback] = useDebouncedCallback(
        (value) => {
            searchRestaurant(value).then(res => {
                setShowSearch(true);
                setResults(res.data);
            });
        },
        300
    );

    const moveToRestaurant = (id: number): void => {
        historyRouter.push(`/restaurant/${id}`);
        setShowSearch(false);
    };

    return (
        <header className="section-header">
            <nav className="navbar navbar-dark navbar-expand p-0 bg-primary">
                <div className="container">
                    <ul className="navbar-nav">
                        <li className="nav-item">
                            <a href="#" className="nav-link">
                                {' '}
                                Telefon: +99812345678{' '}
                            </a>
                        </li>
                        <li className="nav-item dropdown">
                            <a href="#" className="nav-link dropdown-toggle" data-toggle="dropdown">
                                {' '}
                                Polski{' '}
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>

            <section className="header-main border-bottom">
                <div className="container">
                    <div className="row align-items-center">
                        <div className="col-lg-2 col-4">
                            <Link to={'/'} className="brand-wrap">
                                <img className="logo" src="../../../assets/logo.png" />
                            </Link>
                        </div>

                        <div className="col-lg-6 col-sm-12">
                            <div className="search">
                                <div className="input-group w-100">
                                    <input
                                        onChange={e => debouncedCallback(e.target.value)}
                                        type="text"
                                        className="form-control"
                                        placeholder="Search"
                                    />

                                    {!!showSearch && (
                                        <ul className="list-group search">
                                            {results.map(restaurant => (
                                                <li
                                                    onClick={() => moveToRestaurant(restaurant.id)}
                                                    key={restaurant.id}
                                                    className="list-group-item btn-link"
                                                >{restaurant.name}</li>
                                            ))}
                                        </ul>
                                    )}

                                    <div className="input-group-append">
                                        <button className="btn btn-primary" type="submit">
                                            <i className="fa fa-search" />
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div className="col-lg-4 col-sm-6 col-12">
                            <div className="widgets-wrap float-md-right">
                                <div className="widget-header mr-3">
                                    <Link to={'/orders'} className="icon icon-sm rounded-circle border">
                                        <i className="fa fa-shopping-cart" />
                                    </Link>

                                    <span className="badge badge-pill badge-danger notify">{sumOrder}</span>
                                </div>

                                <div className="widget-header icontext">
                                    {user && (
                                        <div
                                            onClick={() => setCollapseDropdown(!collapseDropdown)}
                                            className={`dropdown d-inline-block ${classNames({
                                                show: collapseDropdown
                                            })}`}
                                        >
                                            <div className="icontext mr-4 dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                                <div className="icon icon-sm rounded-circle border">
                                                    <i className="fa fa-user" />
                                                </div>

                                                <div className="text">
                                                    {user.email} <br />
                                                    Konto: <b>{user.type}</b>
                                                </div>
                                            </div>

                                            <div
                                                className={`dropdown-menu dropdown-menu-right ${classNames({
                                                    show: collapseDropdown
                                                })}`}
                                                x-placement="bottom-end"
                                                style={{
                                                    position: 'absolute',
                                                    willChange: 'transform',
                                                    top: '0px',
                                                    left: '0px',
                                                    transform: 'translate3d(0px, 40px, 0px)'
                                                }}
                                            >
                                                <Link to={'/user'} className="dropdown-item">
                                                    Profil
                                                </Link>

                                                <button onClick={() => logout()} className="dropdown-item" type="button">
                                                    <span className="text">Wyloguj</span>
                                                </button>
                                            </div>
                                        </div>
                                    )}

                                    {!user && (
                                        <div className="text">
                                            <span className="text-muted">Witaj!</span>

                                            <div>
                                                <Link to={'/login'}>Zaloguj się</Link> |<Link to={'/register'}>Rejestracja</Link>
                                            </div>
                                        </div>
                                    )}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </header>
    );
};
