// apps/admin-panel/src/app/components/hero/hero.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
    selector: 'tin-hero',
    templateUrl: './hero.component.html',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class HeroComponent {

}

<section class="section-intro">

    <div class="intro-banner-wrap">
        <img src="../../../assets/hero-website-6.jpg" class="w-100 img-fluid">
    </div>

</section>

// apps/client-app/src/app/components/hero.component.tsx
import React from 'react';
import heroBackground from '../../assets/hero-website-6.jpg';

export const Hero = () => {
    return (
        <section className="section-intro">
            <div className="intro-banner-wrap">
                <img src={heroBackground} className="w-100 img-fluid" />
            </div>
        </section>
    )
};
