// apps/admin-panel/src/app/dashboard/containers/login/login-container.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { select, Store } from '@ngrx/store';
import { State } from '../../../+state';
import { LoginUser } from '../../../+state/auth/auth.actions';
import { Observable } from 'rxjs';
import { CommonsState } from '../../../+state/commons/commons.reducer';
import { formQuery } from '../../../+state/commons/commons.selectors';
import { AlertType } from '../../../components/alert/alert.component';

@Component({
    selector: 'tin-login',
    templateUrl: './login-container.component.html',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class LoginContainerComponent {
    formStatus$: Observable<CommonsState> = this.store.pipe(select(formQuery.getForm));

    loginForm: FormGroup;

    readonly AlertType = AlertType;

    constructor(private formBuilder: FormBuilder, private store: Store<State>) {
        this.loginForm = this.formBuilder.group({
            email: ['', Validators.required],
            password: ['', Validators.required]
        });
    }

    onSubmit(): void {
        this.store.dispatch(LoginUser({
            form: this.loginForm.value
        }))
    }

}

<section class="container mt-2">
    <tin-alert
        *ngIf="(formStatus$ | async).customError as error"
        [message]="error.message"
        [type]="AlertType.DANGER"
    ></tin-alert>

    <div class="card mx-auto" style="max-width: 380px;">
        <div class="card-body">
            <h4 class="card-title mb-4">Zaloguj się</h4>

            <form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
                <a href="#" class="btn btn-facebook btn-block mb-2"> <i class="fab fa-facebook-f"></i> &nbsp;  Sign in with Facebook</a>
                <a href="#" class="btn btn-google btn-block mb-4"> <i class="fab fa-google"></i> &nbsp;  Sign in with Google</a>

                <div class="form-group">
                    <input
                        formControlName="email"
                        name="email" class="form-control" placeholder="Email" type="email">
                </div> <!-- commons-group// -->

                <div class="form-group">
                    <input
                        formControlName="password"
                        name="password" class="form-control" placeholder="Password" type="password">
                </div> <!-- commons-group// -->

                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">Zaloguj </button>
                </div> <!-- commons-group// -->
            </form>
        </div> <!-- card-body.// -->
    </div> <!-- card .// -->

    <div class="mx-auto" style="max-width: 580px;">
        <p class="text-center mt-4">Nie masz konta? <a [routerLink]="['/register']">Zarejestruj się</a></p>
        <br>

        <hr/>
        <p class="text-center mt-4">Jeżeli jesteś pracownikiem to kliknij <a [routerLink]="['/createEmployee-login']">tutaj</a> aby się zalogować.</p>
        <br>
    </div>
</section>

// apps/client-app/src/app/containers/login.container.tsx
import React from 'react';
import { useForm } from 'react-hook-form';
import { useDispatch } from 'react-redux';
import { loginAction } from '../+state/auth/auth.actions';

type FormData = {
    email: string;
    username: string;
}

export const LoginContainer = () => {
    const { handleSubmit, register, errors } = useForm<FormData>();
    const dispatch = useDispatch();

    const onSubmit = values => {
        console.log(values);
        const { email, password } = values;

        dispatch(loginAction(email, password));
    };

    return (
        <section className="container mt-2">
            <div className="card mx-auto" style={{maxWidth: '380px'}}>
                <div className="card-body">
                    <h4 className="card-title mb-4">Zaloguj się</h4>

                    <form onSubmit={handleSubmit(onSubmit)}>
                        <a href="#" className="btn btn-facebook btn-block mb-2">
                            <i className="fab fa-facebook-f"/> &nbsp;  Sign in with Facebook
                        </a>

                        <a href="#" className="btn btn-google btn-block mb-4">
                            <i className="fab fa-google"/> &nbsp;  Sign in with Google
                        </a>

                        <div className="form-group">
                            <input
                                ref={register}
                                name="email"
                                className="form-control"
                                placeholder="Email"
                                type="email"
                            />
                        </div>

                        <div className="form-group">
                            <input
                                ref={register}
                                name="password"
                                className="form-control"
                                placeholder="Password"
                                type="password"
                            />
                        </div>

                        <div className="form-group">
                            <button type="submit" className="btn btn-primary btn-block">Zaloguj</button>
                        </div>
                    </form>
                </div>
            </div>

            <div className="mx-auto" style={{maxWidth: '580px'}}>
                <p className="text-center mt-4">Nie masz konta? <a >Zarejestruj się</a></p>
                <br/>
            </div>
        </section>
    );
};
