// apps/admin-panel/src/app/dashboard/containers/user-reservations/user-reservations-container.component.ts
import { ChangeDetectionStrategy, Component, OnInit } from '@angular/core';
import { select, Store } from '@ngrx/store';
import { Observable } from 'rxjs';
import { Reservation, ReservationStatus } from '@bon-appetit/interfaces';
import { reservationsQuery } from '../../../+state/reservations/reservations.selectors';
import { State } from '../../../+state';
import { LoadReservationsRestaurant, LoadReservationsUser } from '../../../+state/reservations/reservations.actions';
import { ViewFetchOrdersUser } from '../../../+state/viewOrders/viewOrders.actions';
import { SelectedRestaurant } from '../../../+state/restaurants/restaurants.actions';
import { Router } from '@angular/router';
import { AlertType } from '../../../components/alert/alert.component';

@Component({
    selector: 'tin-user-reservations-container',
    templateUrl: './user-reservations-container.component.html',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class UserReservationsContainerComponent implements OnInit {
    reservations$: Observable<Reservation[]> = this.store.pipe(select(reservationsQuery.getReservations));

    readonly AlertType = AlertType;

    constructor(private store: Store<State>,
                private router: Router) {}

    ngOnInit() {
        this.store.dispatch(LoadReservationsUser());
    }

    showRestaurant(restaurantId: number): void {
        this.store.dispatch(SelectedRestaurant({ restaurantId }));

        this.router.navigate(['/company/restaurants', restaurantId]);
    }

    getDate(date: Date): string {
        return new Date(date).toLocaleDateString();
    }

    getClassReservationStatus(status: ReservationStatus): string {
        switch (status) {
            case ReservationStatus.PRZYJETO: {
                return 'badge-success';
            }
            case ReservationStatus.ANULOWANO: {
                return 'badge-danger';
            }
            case ReservationStatus.ZAKONCZONO: {
                return 'badge-secondary'
            }
        }
    }
}

<ng-container
    *ngIf="(reservations$ | async).length > 0; else empty"
>
    <main
        *ngFor="let reservation of (reservations$ | async)"
        class="col-md-12 mb-4">

        <article class="card">
            <header class="card-header">
                <strong class="d-inline-block mr-3">ID rezerwacji: {{ reservation.id }}</strong>
                <span>Data rezerwacji: {{ getDate(reservation?.date) }}, {{ reservation.hour }}</span>
            </header>

            <div class="card-body">
                <div class="row">
                    <div class="status-badge">
                        <span [ngClass]="getClassReservationStatus(reservation.status)" class="badge px-4 py-2">{{ reservation.status }}</span>
                    </div>

                    <div class="col-md-8">
                        <h4 class="text-primary"><strong>{{ reservation.restaurant?.name }}</strong></h4>

                        <ul>
                            <li>Telefon: <strong>{{ reservation.restaurant?.phoneNumber }}</strong></li>
                            <li>Email: <strong>{{ reservation.restaurant?.email }}</strong></li>
                        </ul>

                        <div class="block">
                            <h6 class="text-muted">Adres:</h6>

                            <ul>
                                <li>Miasto: <strong>{{ reservation.restaurant?.city }}</strong></li>
                                <li>Ulica: <strong>{{ reservation.restaurant?.street }}</strong></li>
                                <li>Number budynku: <strong>{{ reservation.restaurant?.numberOfBuilding }}</strong></li>
                                <li>Kod pocztowy: <strong>{{ reservation.restaurant?.postalCode }}</strong></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <h6 class="text-muted">Stolik</h6>

                        <span class="text-primary">
                        {{ reservation.table.name }}
                    </span>
                        <p>
                            <span class="b">{{ reservation.peopleCount}} / {{ reservation.table.maxPeopleCount }}</span>
                        </p>

                        <button (click)="showRestaurant(reservation.restaurantId)" type="button" class="btn btn-primary">O restauracji</button>
                    </div>
                </div>
                <!-- row.// -->
            </div>
            <!-- card-body .// -->
        </article>
        <!-- order-group.// -->
    </main>
</ng-container>

<ng-template #empty>
    <tin-alert
        [type]="AlertType.PRIMARY"
        [message]="'Nie ma aktualnie żadnych rezerwacji.'"
    ></tin-alert>
</ng-template>

// apps/client-app/src/app/containers/user-reservations.container.tsx
import React, { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { State } from '../+state';
import { fetchReservationsAction } from '../+state/reservations/reservations.actions';
import { fetchAndSelectRestaurantAction } from '../+state/restaurants/restaurants.actions';
import { Alert, AlertType } from '../components/alert.component';
import { ReservationStatus } from '@bon-appetit/interfaces';

export const UserReservations = (props) => {
    const user = useSelector((state: State) => state.authData.user);
    const { reservations, loaded } = useSelector((state: State) => state.reservationsData);
    const dispatch = useDispatch();

    useEffect(() => {
        if(user) {
            dispatch(fetchReservationsAction(user.id));
        } else {
            props.history.push('/');
        }

    }, []);

    const getDate = (date: Date): string => {
        return new Date(date).toLocaleDateString();
    };

    const showRestaurant = (restaurantId: number) => {
        dispatch(fetchAndSelectRestaurantAction(restaurantId));

        props.history.push(`/restaurant/${restaurantId}`);
    };

    const getClassReservationStatus = (status: ReservationStatus): string => {
        switch (status) {
            case ReservationStatus.PRZYJETO: {
                return 'badge-success';
            }
            case ReservationStatus.ANULOWANO: {
                return 'badge-danger';
            }
            case ReservationStatus.ZAKONCZONO: {
                return 'badge-secondary'
            }
        }
    };

    return (
        <>
            <div>
                {!!reservations.length ? reservations.map(reservation => {
                    return (
                        <main
                            key={reservation.id}
                            className="col-md-12 mb-4">
                            <article className="card">
                                <header className="card-header">
                                    <strong className="d-inline-block mr-3">ID rezerwacji: {reservation.id}</strong>
                                    <span>Data rezerwacji: {getDate(reservation.date)}, {reservation.hour}</span>
                                </header>

                                <div className="card-body">
                                    <div className="row">
                                        <div className="status-badge">
                                            <span className={`badge px-4 py-2 ${getClassReservationStatus(reservation.status)}`}>{reservation.status}</span>
                                        </div>

                                        <div className="col-md-8">
                                            <h4 onClick={() => showRestaurant(reservation.restaurantId)}
                                                className="text-primary">
                                                <strong>{reservation.restaurant.name}</strong>
                                            </h4>

                                            <ul>
                                                <li>
                                                    Telefon: <strong>{reservation.restaurant.phoneNumber}</strong>
                                                </li>
                                                <li>
                                                    Email: <strong>{reservation.restaurant.email}</strong>
                                                </li>
                                            </ul>

                                            <div className="block">
                                                <h6 className="text-muted">Adres:</h6>

                                                <ul>
                                                    <li>
                                                        Miasto: <strong>{reservation.restaurant.city}</strong>
                                                    </li>
                                                    <li>
                                                        Ulica: <strong>{reservation.restaurant.street}</strong>
                                                    </li>
                                                    <li>
                                                        Number budynku: <strong>{reservation.restaurant.numberOfBuilding}</strong>
                                                    </li>
                                                    <li>
                                                        Kod pocztowy: <strong>{reservation.restaurant.postalCode}</strong>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>

                                        <div className="col-md-4">
                                            <h6 className="text-muted">Stolik</h6>

                                            <span className="text-primary">{reservation.table.name}</span>
                                            <p>
                                                <span className="b">{reservation.peopleCount} / {reservation.table.maxPeopleCount}</span>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </article>
                        </main>
                    );
                }) : (
                    <div>
                        <Alert type={AlertType.PRIMARY} message={"Nie masz aktualnie rezerwacji"}/>
                    </div>
                )}
            </div>
        </>
    );
};
