// apps/client-app/src/app/containers/orders.container.tsx
import React from 'react';
import { Title } from '../components/title';
import { useDispatch, useSelector } from 'react-redux';
import { State } from '../+state';
import classNames from 'classnames';
import { payOrdersAction } from '../+state/orders/orders.actions';
import { Spinner } from '../components/spinner';
import { Alert, AlertType } from '../components/alert.component';

export const Orders = () => {
    const { orders, sumOrder, isPay } = useSelector((state: State) => state.ordersData);
    const commons = useSelector((state: State) => state.commonsData);
    const dispatch = useDispatch();

    const pay = () => {
      dispatch(payOrdersAction(orders.filter(order => order.paid === 0)));
    };

    return (
        <>
            <Title title={'Zamówienia'} />

            <section className="section-content padding-y">
                <div className="container">
                    {commons.loaded ? (
                        <div className="row">
                            <div className="mx-auto" style={{ maxWidth: '920px' }}>
                                {commons.success && <Alert type={AlertType.SUCCESS} message={'Przyjęto zamówienie'} />}

                                {commons.error && (
                                    <Alert
                                        type={AlertType.DANGER}
                                        message={
                                            'Wystąpiły problemy podczas zapłaty! Spróbuj ponownie.'
                                        }
                                    />
                                )}
                            </div>

                            <main
                                className={`${classNames({
                                    'col-md-9': !isPay,
                                    'col-md-12': isPay
                                })}`}
                            >
                                <div className="card">
                                    <table className="table table-borderless table-shopping-cart">
                                        <thead className="text-muted">
                                        <tr className="small text-uppercase">
                                            <th scope="col">Danie</th>
                                            <th scope="col" style={{ width: '120px' }}>
                                                Ilość
                                            </th>
                                            <th scope="col" style={{ width: '120px' }}>
                                                Cena
                                            </th>
                                            <th scope="col" className="text-right" style={{ width: '200px' }} />
                                        </tr>
                                        </thead>

                                        <tbody>
                                        {!!orders.length &&
                                        orders.map(order => {
                                            return (
                                                <tr key={order.id}>
                                                    <td>
                                                        <figure className="itemside">
                                                            <div className="aside">
                                                                <img src={order.dish.imageUrl} className="img-sm" alt="" />
                                                            </div>

                                                            <figcaption className="info">
                                                                <a href="#" className="title text-dark">
                                                                    {order.dish.name}
                                                                </a>
                                                                <p className="text-muted small">
                                                                    Status:
                                                                    <b
                                                                        className={classNames({
                                                                            'text-success': order.paid,
                                                                            'text-danger': !order.paid
                                                                        })}
                                                                    >
                                                                        {order.status}
                                                                    </b>
                                                                </p>
                                                            </figcaption>
                                                        </figure>
                                                    </td>

                                                    <td>
                                                        <div className="form-row">
                                                            <div className="form-group col-md flex-grow-0">
                                                                <div className="input-group input-spinner">
                                                                    <div className="input-group-prepend">
                                                                        <span className="text-center">{order.count}</span>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </td>

                                                    <td>
                                                        <div className="price-wrap">
                                                            <var className="price">{order.sumPriceDish} zł</var>
                                                            <small className="text-muted">{order.dish.price} zł za sztukę </small>
                                                        </div>
                                                    </td>

                                                    <td
                                                        className={`text-right ${classNames({
                                                            'd-none': order.paid
                                                        })}`}
                                                    >
                                                        <button className="btn btn-danger">Usuń</button>
                                                    </td>
                                                </tr>
                                            );
                                        })}

                                        {!orders.length && (
                                            <tr>
                                                <td>hhhh</td>
                                            </tr>
                                        )}
                                        </tbody>
                                    </table>

                                    <div
                                        className={`card-body border-top ${classNames({
                                            'd-none': isPay
                                        })}`}
                                    >
                                        <button
                                            onClick={() => pay()}
                                            type="button"
                                            className="btn btn-primary float-md-right"
                                        >
                                            Zapłać <i className="fa fa-chevron-right" />
                                        </button>
                                    </div>
                                </div>
                            </main>

                            <aside
                                className={`col-md-3 ${classNames({
                                    'd-none': isPay
                                })}`}
                            >
                                <div className="card">
                                    <div className="card-body">
                                        <dl className="dlist-align">
                                            <dt>Suma do zapłaty:</dt>
                                            <dd className="text-right h5">
                                                <strong>{sumOrder} zł</strong>
                                            </dd>
                                        </dl>
                                    </div>
                                </div>
                            </aside>
                        </div>
                    ) : (
                        <Spinner />
                    )}
                </div>
            </section>
        </>
    );
};

// apps/admin-panel/src/app/dashboard/containers/orders/orders-container.component.ts
import { Component, OnInit } from '@angular/core';
import { select, Store } from '@ngrx/store';
import { FetchOrdersUser, PayOrders, RemoveOrder } from '../../../+state/orders/orders.actions';
import { ordersQuery } from '../../../+state/orders/orders.selectors';
import { State } from '../../../+state';
import { Observable } from 'rxjs';

@Component({
    selector: 'tin-orders',
    templateUrl: './orders-container.component.html'
})
export class OrdersContainerComponent implements OnInit {
    orders$ = this.store.pipe(select(ordersQuery.getOrders));
    paid$: Observable<boolean> = this.store.pipe(select(ordersQuery.getIsPay));
    getSumOrders$: Observable<number> = this.store.pipe(select(ordersQuery.getSumCountOrder));

    constructor(private store: Store<State>) {
    }

    ngOnInit(): void {
        this.store.dispatch(FetchOrdersUser());
    }

    removeOrder(orderId: number): void {
        this.store.dispatch(RemoveOrder({ orderId }));
    }

    payOrders(): void {
        this.store.dispatch(PayOrders());
    }
}

<tin-title [title]="'Zamówienia'"> </tin-title>

<section class="section-content padding-y">
    <div class="container">
        <div class="row">
            <main
                [ngClass]="(paid$ | async) ? 'col-md-12' : 'col-md-9'"
                >
                <div class="card">
                    <table class="table table-borderless table-shopping-cart">
                        <thead class="text-muted">
                            <tr class="small text-uppercase">
                                <th scope="col">Danie</th>
                                <th scope="col" width="120">Ilość</th>
                                <th scope="col" width="120">Cena</th>
                                <th scope="col" class="text-right" width="200"></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr *ngFor="let order of orders$ | async">
                                <td>
                                    <figure class="itemside">
                                        <div class="aside"><img src="{{ order.dish?.imageUrl }}" class="img-sm" /></div>

                                        <figcaption class="info">
                                            <a href="#" class="title text-dark">{{ order.dish?.name }}</a>
                                            <p class="text-muted small">
                                                Status:
                                                <b [ngClass]="(paid$ | async) ? 'text-success' : 'text-danger'"
                                            > {{ order.status }}</b>
                                            </p>
                                        </figcaption>
                                    </figure>
                                </td>
                                <td>
                                    <div class="form-row">
                                        <div class="form-group col-md flex-grow-0">
                                            <div
                                                *ngIf="!(paid$ | async); else count"
                                                class="input-group input-spinner">
                                                <div
                                                    class="input-group-prepend">
                                                    <button class="btn btn-light" id="button-plus" type="button">+</button>
                                                </div>

                                                <input
                                                    [value]="order.count"
                                                    class="form-control" type="text" />

                                                <div class="input-group-append">
                                                    <button class="btn btn-light" id="button-minus" type="button">−</button>
                                                </div>
                                            </div>

                                            <ng-template #count>
                                                <span class="text-center">{{ order.count }}</span>
                                            </ng-template>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <div class="price-wrap">
                                        <var class="price">${{ order.sumPriceDish }}</var>
                                        <small class="text-muted"> ${{ order.dish.price }} za sztukę </small>
                                    </div>
                                    <!-- price-wrap .// -->
                                </td>

                                <td
                                    [ngClass]="(paid$ | async) ? 'd-none' : null"
                                    class="text-right">
                                    <button
                                        (click)="removeOrder(order.id)"
                                        class="btn btn-danger">Usuń</button>
                                </td>
                            </tr>
                        </tbody>
                    </table>

                    <div class="card-body border-top">
                        <button
                            [ngClass]="(paid$ | async) ? 'd-none' : null"
                            (click)="payOrders()"
                            type="button"
                            class="btn btn-primary float-md-right">
                            Zapłać <i class="fa fa-chevron-right"></i>
                        </button>
                    </div>
                </div>
                <!-- card.// -->

            </main>
            <!-- col.// -->

            <aside
                [ngClass]="(paid$ | async) ? 'd-none' : null"
                class="col-md-3">
                <div class="card">
                    <div class="card-body">
                        <dl class="dlist-align">
                            <dt>Suma do zapłaty:</dt>
                            <dd class="text-right  h5"><strong>{{ getSumOrders$ | async }}zł</strong></dd>
                        </dl>
                    </div>
                    <!-- card-body.// -->
                </div>
                <!-- card .// -->
            </aside>
            <!-- col.// -->
        </div>
    </div>
    <!-- container .//  -->
</section>
